version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "id"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gp5zbb2zvoai"
s3_prefix = "id"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
